### ISSUE TITLE
绿守不兼容安卓P

### ISSUE THREAD

**Issue by 3acherMAN** [tiann/EXposed#100]
手机型号：一加5t
ROM版本：氧os 安卓P
Xposed模块：
APP：绿色守护

问题描述：
绿色守护4.5.1在安卓P上使用会闪退，是绿守的问题，所以希望适配低版本的绿色守护，例如4.3.2
其他Magisk模块：
无
补充：并不是taichi的问题，而是绿守4.5.1和安卓P冲突，所以即使更新了这个软件，很多人也是无法使用，例如我。

**Comment by tiann** [comment]
我使用正常。

知道冲突的原因么？

**Comment by 3acherMAN** [comment]
并不知道冲突的原因，看酷安评论区的人们说，应该是绿守4.5.1版本的问题，是4.5.1不支持安卓P，另外我使用4.3.2版本不会闪退。但是，这没有办法解释你使用正常。

**Comment by 3acherMAN** [comment]
[greenify.zip](https://github.com/tiann/EXposed/files/2806077/greenify.zip)
一个是官方版本，一个是破解的

**Comment by 3acherMAN** [comment]
大佬，怎么样？想请教一下你是怎么使用4.5.1的

**Comment by wangyaweigg** [comment]
大佬，怎么在这个软件里面关注你
