### ISSUE TITLE
BUG反馈：lataclysm作用后，应用卡死

### ISSUE THREAD

**Issue by afteragain** [tiann/EXposed#101]
手机型号：红米NOTE5
ROM版本：MIUI10 Android8.1
Xposed模块：lataclysm
APP：钉钉，UC浏览器等等

问题描述：
lataclysm作用于应用后，会导致应用打不开（点击无反应或者卡首界面）
其他Magisk模块：
MM管理器
补充：
xposed模块只勾选lataclysm这一个模块也会导致应用卡死

**Comment by afteragain** [comment]
还是老样子

**Comment by afteragain** [comment]
还是老样子

**Comment by afteragain** [comment]
正式版4.2.3，应用也打不开

**Comment by tiann** [comment]
这两个应用可能有检测，试下其他app是否可行

**Comment by afteragain** [comment]
QQ，高德，酷安，和飞信，菜鸟裹裹都是一样的现象

**Comment by afteragain** [comment]
在装有xposed的手机上试，钉钉，高德没有问题

**Comment by tiann** [comment]
尽量升级9.0系统吧，我miui没这问题。9.0以下不会修复了。
