### ISSUE TITLE
太极4.2.0.4中不显示模块管理

### ISSUE THREAD

**Issue by w211691** [tiann/EXposed#113]
手机型号：小米MIX2S
ROM版本：MIUI10
Xposed模块：所有
APP：所有

问题描述：太极中没有模块管理，无法启动任何Xposed模块
<img src=http://thyrsi.com/t6/665/1548848407x2890211845.png />
其他Magisk模块：MM管理器

补充：机器曾经安装过xposed框架，后来停用了，是这个的影响吗

**Comment by tiann** [comment]
是的

**Comment by w211691** [comment]
> 是的

了解了，那我卸载掉Xposed框架试一下
