### ISSUE TITLE
系统双开太极无法启动模块

### ISSUE THREAD

**Issue by Cantg1222** [tiann/EXposed#12]
模块已双开，提示magisk太极需要root权限才可以启动模块

**Comment by tiann** [comment]
双开暂时有问题，以后修复

**Comment by tiann** [comment]
暂时使用 Island 可以满足双开的要求。

**Comment by tiann** [comment]
系统记的双开无需双开太极，直接双开对应的应用；主太极中勾选的模块也可对双开的应用生效。
