### ISSUE TITLE
【建议】太极是否考虑去掉模块版本限制支持？

### ISSUE THREAD

**Issue by 06ji** [tiann/EXposed#121]
手机型号：小米5
ROM版本：miui10 8.10.12
Xposed模块：无
APP：无

问题描述：有的模块更新太频繁，太极跟不上更新进度，是否考虑去掉版本限制支持？直接支持新旧版本

其他Magisk模块：无

补充：

**Comment by cutepan** [comment]
好似抖音助手一样，有些旧的版本是免费的现在新的版本都收费，我都不用新的版本~

**Comment by johoney** [comment]
赞同
