### ISSUE TITLE
QX部分功能失效

### ISSUE THREAD

**Issue by kiwiape** [tiann/EXposed#138]
手机型号：红米Note5
ROM版本：MIUI10 开发版 9.1.17 （Android 8.1.0）
Xposed模块：QX 1.21_6.23
APP：QQ
太极版本：Magisk 4.0，APP 4.2.3

问题描述：
1. “红包”“自动回复”两个设置菜单无法点进去，只能出现下图状态
![](https://i.loli.net/2019/02/01/5c5330bec8b0c.png)
1. 已勾选“长按笑脸发送网络表情”，仍然无法长按弹出界面。并且此前版本可以弹出，但无法发送图片表情（选好要发的表情，点确定之后，对话框关闭，啥事都没发生，预测是模块没有存图权限）
![](https://i.loli.net/2019/02/01/5c5331fa958b0.png)

其他Magisk模块：
![](https://i.loli.net/2019/02/01/5c5332819098e.png)

**Comment by xiaohuang2004** [comment]
出现这种情况正常吧，我用QX也发现自动回复有时没有用，自己看自动回复消息发送出去了，但是对方却没有收到。
fkzhang说了，对于非官方xposed框架环境运行导致的问题，只能尽量适配，有问题也没办法

**Comment by tiann** [comment]
升级9.0

**Comment by kiwiape** [comment]
> 出现这种情况正常吧，我用QX也发现自动回复有时没有用，自己看自动回复消息发送出去了，但是对方却没有收到。
> fkzhang说了，对于非官方xposed框架环境运行导致的问题，只能尽量适配，有问题也没办法

一点都不正常，我这是根本点不开这两个菜单，而不是功能间歇性失效。希望你能理解透彻我所表达的意思。

**Comment by kiwiape** [comment]
> 升级9.0

大佬的回答实在是太过干脆。
一来MIUI并未提供9.0的更新
二来升级就一定能解决吗
三是隔壁edxposed是不存在这三个bug的，所以还是来提交了这个issue，想着应该是能够修复的。

**Comment by kiwiape** [comment]
更新一下相关进度，给遇到同样情况的参考：
目前菜单已经能够正常打开，自己就好了，不知道为什么。表情包还是发不出。
期间切换过edxposed，用过ed的管理程序对QQ进行speed编译，也在ed的管理程序里把黑名单切换成了白名单。
具体是哪个起效的，不清楚，可以尝试。
