### ISSUE TITLE
小米8SE，添加应用后，应用闪退

### ISSUE THREAD

**Issue by Travisss** [tiann/EXposed#14]
跟旧版的太极类似，小米8SE在9.1.14之后的版本，添加的应用会闪退无法打开，即使不启用任何模块。日志：
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/sirius/sirius:9/PKQ1.181121.001/9.1.21:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 28115, tid: 28120, name: Jit thread pool  >>> <pre-initialized> <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x43d192e0
    r0  00000000  r1  ed15834c  r2  00000000  r3  00000000
    r4  e6287000  r5  00000000  r6  ec22581a  r7  ec2260e9
    r8  00000043  r9  ec275374  r10 ec276e9c  r11 0000005b
    ip  e65938c8  sp  e65938dc  lr  ec0487b9  pc  43d192e0

backtrace:
    #00 pc 311192e0  /dev/ashmem/dalvik-main space (region space) (deleted)
    #01 pc 002507b5  /system/lib/libart.so (offset 0x243000) (art::jit::JitCompileTask::Run(art::Thread*)+484)

**Comment by tiann** [comment]
小米内测版的 ROM 吗？

**Comment by Travisss** [comment]
是最新内测，但是上周开发版下，安装旧版太极，创建的应用也打不开，即使不启用任何模块。请问从日志里能看出什么问题吗？

**Comment by tiann** [comment]
疑似小米对 虚拟机 做了改动，我需要一个包看一下。能否把 /system/lib/libart.so 发给我看看？

**Comment by Travisss** [comment]
> 疑似小米对 虚拟机 做了改动，我需要一个包看一下。能否把 /system/lib/libart.so 发给我看看？

http://t.cn/E5WRQ39

**Comment by Travisss** [comment]
> 疑似小米对 虚拟机 做了改动，我需要一个包看一下。能否把 /system/lib/libart.so 发给我看看？

文件已打包，非常感谢

**Comment by tiann** [comment]
fixed in https://github.com/tiann/EXposed/releases/tag/4.1.4
