### ISSUE TITLE
magisk4.0版卡米

### ISSUE THREAD

**Issue by Lay233** [tiann/EXposed#146]
手机型号：红米note3全网通
ROM版本：MIUI10.2稳定版
Xposed模块：无
APP：

问题描述：刷入magisk4.0版后卡米，之前刷3.6两个版版本都卡米。

其他Magisk模块：高级设置

补充：希望能适配MIUI10

**Comment by 06ji** [comment]
抓log

**Comment by tiann** [comment]
支持miui 10，刷之前把手机清干净就行了。
