### ISSUE TITLE
请求支持JustTrustMe

### ISSUE THREAD

**Issue by tanghengvip** [tiann/EXposed#156]
## 模块名字
JustTrustMe （ Github开源地址: https://github.com/Fuzion24/JustTrustMe ）

## 模块用途
JustTrustMe是一个去掉https证书校验的xposed hook插件，去掉之后就可以抓取做了证书校验的app的数据包。（如能支持，将会给相关工作人员带来极大方便！）

## 模块版本号
v2

## 模块安装包
https://github.com/Fuzion24/JustTrustMe/releases/download/v.2/JustTrustMe.apk

**Comment by sunzongzheng** [comment]
面具闪退

**Comment by tiann** [comment]
@sunzongzheng 请不要讨论无关内容。

**Comment by sunzongzheng** [comment]
@tiann 装了这个版本以后面具闪退。这个模块以前没有用过，使用了一下没有用成功，不能确定是否是姿势的原因，所以没有反馈这个模块的使用问题 :sob:

**Comment by tiann** [comment]
理论上425已经支持了了，没有回应我就关了。
