### ISSUE TITLE
MIUI双开微信QQ无法启动

### ISSUE THREAD

**Issue by 1071239216** [tiann/EXposed#163]
手机型号：小米MIX2
ROM版本：MIUI 10 9.1.24
Xposed模块：无
APP：
QQ，微信

问题描述：
通过MIUI自带应用双开，双开微信，QQ，太极并进行优化之后，启动QQ和微信弹出如下提示（见补充），之后黑屏无法操作，手机锁屏后重新打开即恢复正常，其他模块双开正常

其他Magisk模块：无

补充：
![_20190201130426](https://user-images.githubusercontent.com/25280272/52103701-ee948d80-2621-11e9-905f-15ac513fe305.jpg)
![_20190201130431](https://user-images.githubusercontent.com/25280272/52103702-ee948d80-2621-11e9-80c9-e10c5f04fcbb.jpg)

**Comment by tiann** [comment]
按照双开教程操作的吗？

**Comment by 1071239216** [comment]
> 按照双开教程操作的吗？

是的，按照双开教程，把软件和太极都双开

**Comment by tiann** [comment]
软件有重新创建吗？

**Comment by 1071239216** [comment]
找到问题的解决方法了，首先按照教程创建应用分身（包括所需要的应用），然后在分身出来的太极里用正常的安装包创建应用，然后直接优化就能用了。

**Comment by Melodyknit** [comment]
使用体验极差，我也出现这种问题
