### ISSUE TITLE
关于太极阳与magisk版本兼容问题

### ISSUE THREAD

**Issue by kid-oh** [tiann/EXposed#173]
手机型号：小米5
ROM版本：havoc 9.0
Xposed模块：太极阳
APP：

问题描述：作者你好，在电报群里有机友反应用面具16的版本会很稳定，太极不会失效。之前我用18的面具配google助手的edxposed或您的太极阳，都只生效一次后重启后或更新系统内核就掉了，并且怎么卸载重装都不会再生效。然后刚刚我回滚到16.7的面具后，很稳定，怎么都不会掉，所以希望您能检查一下是不是面具兼容问题

其他Magisk模块：

补充：

**Comment by 06ji** [comment]
同意，就怕每次taichi越更新，面具越降级

另外，我特意双清重刷系统，第一时间刷进面具和taichi4.0，依然是阴，必须要再次降级16.6才能用，就怕taichi以后越更新，面具越降级

**Comment by Jack0001** [comment]
最新4.2.5太极app，在我手机上经过测试貌似已经修复了。
