### ISSUE TITLE
4.0的magisk版本应用变量无法使用问题

### ISSUE THREAD

**Issue by zeemars** [tiann/EXposed#178]
手机型号：一加6
ROM版本：测试14版
Xposed模块：应用变量
APP：应用变量

问题描述：
应用变量在3.6b无法正常使用，后来换到3.6a正常使用可以更换手机型号，但是到了4.0后怎样设置或者切换应用变量的版本均无法生效，系统为一加6 安卓9.0。
其他Magisk模块：

补充：

**Comment by a2212997715** [comment]
应用变量只支持3.210
