### ISSUE TITLE
一加6氢os9.0 

### ISSUE THREAD

**Issue by zichenya** [tiann/EXposed#18]
刷了太极模块之后系统无限自动重启。软重启。

**Comment by ZYMirror** [comment]
是不是刷了a版，试试换成b版

**Comment by Qitain** [comment]
> 是不是刷了a版，试试换成b版

求无root刷入方法

**Comment by ZYMirror** [comment]
> > 是不是刷了一个版，试试换成b版
> 
> 求无根刷入方法

面具就是root啊

**Comment by Qitain** [comment]
> > > 是不是刷了一个版，试试换成b版
> > 
> > 
> > 求无根刷入方法
> 
> 面具就是root啊

不是说最新版的不需要root就可以用太极么

**Comment by hxsstime** [comment]
> > > > 是不是刷了一个版，试试换成b版
> > > 
> > > 
> > > 求无根刷入方法
> > 
> > 
> > 面具就是root啊
> 
> 不是说最新版的不需要root就可以用太极么

太极不需要root，但是Magisk版肯定要Root啊……这个版本主要应对的是系统级应用啊……

**Comment by tiann** [comment]
暂时使用 3.2-b 即可。

**Comment by sycpiek** [comment]
一加6 如何不被系统杀死呢？
