### ISSUE TITLE
magisk版太极双开添加模块失败

### ISSUE THREAD

**Issue by LotusHaner** [tiann/EXposed#189]
系统：安卓8.1MIUI10，
太极版本：4.2.1.2
双开应用、太极、模块后，勾选模块不成功，显示需要magisk给予root权限，但双开的magisk无法使用。
然而，模块其实可以正常使用，只是太极会显示失败，希望能修复一下

**Comment by Cloudy-Kumori** [comment]
模块是怎么做到正常使用的

**Comment by tiann** [comment]
用island
