### ISSUE TITLE
支持Xposed edge pro

### ISSUE THREAD

**Issue by darkaccount** [tiann/EXposed#190]
## 模块名字
Xposed edge pro
## 模块用途
该模块为您提供了手势控制，重点控制等智能触发器。
## 模块版本号
5.2.3
## 模块安装包
https://play.google.com/store/apps/details?id=com.jozein.xedgepro
###其他
好像只支持普通的，不支持pro版？

**Comment by caliban511** [comment]
支持的，我是PLAY的PRO版，使用正常。
