### ISSUE TITLE
安装模块后，强制停止也没反应

### ISSUE THREAD

**Issue by ZjVirus** [tiann/EXposed#2]
在VirtualXposed里边是可以的，在太极就不行，没有反应。三星S8-安卓7.0

**Comment by tiann** [comment]
请说明具体情况。比如，什么模块，没反应具体指的什么；不然谁能看懂你在说啥？

**Comment by ZjVirus** [comment]
不好意思，安装的MDWechat,强制停止后，启动微信，没有变化。但是微信增强可以用。微信6.6.7 play版，MD 3.2

**Comment by tiann** [comment]
MDWechat 怎么用的？

**Comment by ZjVirus** [comment]
安装MD模块，打开MD总开关，生成配置文件，停止微信，然后启动微信，操作不对？

**Comment by ZjVirus** [comment]
换了MD 3.1.0
版本的可以了
