### ISSUE TITLE
微信从后台切到前台必然闪退

### ISSUE THREAD

**Issue by lcmylife** [tiann/EXposed#204]
手机型号：Sony XZP
ROM版本：9.0
Xposed模块：微信增强、指纹支付、
APP：微信7.0

问题描述:微信放到后台，然后打开其它程序，再快速地切回前台，必然发生闪退。只是把微信添加进太极，没有勾选模块，排除是模块的问题。

其他 Magisk 模块：

**Comment by tiann** [comment]
https://www.lanzous.com/i32eyzi 试下这个

**Comment by lcmylife** [comment]
好了，不闪退了，感谢大大！
