### ISSUE TITLE
小米6X(HAVOC-2.1-PIE)启用核心破解无限软重启

### ISSUE THREAD

**Issue by bahkxiao** [tiann/EXposed#210]
手机型号：小米6x
ROM版本：HAVOC-2.1(Pie)
Xposed模块：核心破解
APP：

问题描述：启用核心破解模块重启后，3-5秒（应该是在等待太极启动）之后软重启。

其他Magisk模块：QXposed 运动修改 指纹支付

补充：

**Comment by bahkxiao** [comment]
均是最新版本

**Comment by tiann** [comment]
核心破解的问题，与太极没什么关系。虽然这个模块也是我写的，但我也没有打算让这个模块支持所有ROM。想用这个模块的话用能用的ROM。
