### ISSUE TITLE
红米note2无法安装任何APP

### ISSUE THREAD

**Issue by wang-peak** [tiann/EXposed#216]
手机型号：红米note2
ROM版本：安卓5.0.2，MIUI9.6
Xposed模块：
APP：所有

问题描述：启用Tai Chi 后手机无法安装任何APP，停用后正常.

其他Magisk模块：

补充：

**Comment by tiann** [comment]
使用说明讲过了，8.0以下的系统不要尝试。出现任何问题我也不会去解决。
