### ISSUE TITLE
蚂蚁&庄园模块无法正常运行

### ISSUE THREAD

**Issue by fjzxz** [tiann/EXposed#217]
手机型号：小米6 sagit
ROM版本：MIUI 10 9.1.28
Xposed模块：蚂蚁&庄园
APP：支付宝

问题描述：在太极中创建支付宝应用，勾选蚂蚁&庄园模块，结束运行支付宝后蚂蚁&庄园模块没有作用，打开蚂蚁&庄园模块，点击帮助内的模块检测，点击继续没有任何反应，模块没有被正常加载，无法使用

其他Magisk模块：无

补充：太极版本是定海神针·4.2.5，蚂蚁&庄园模块是1.1.2版本，支付宝是10.1.55.6000

**Comment by tiann** [comment]
这模块本身有问题，只能用一次，与太极无关。

**Comment by fjzxz** [comment]
> 这模块本身有问题，只能用一次，与太极无关。

好吧，谢谢
