### ISSUE TITLE
QX奔溃闪退 q++1.1.9闪退 q++1.1.10不生效

### ISSUE THREAD

**Issue by EarlDong** [tiann/EXposed#22]
手机型号：小米8探索版
ROM版本：MIUI开发版 9.1.17
Xposed模块：QX模块  q++
APP：QQ

问题描述：QX奔溃严重 q++1.1.9 闪退无响应 q++1.1.10无法生效

其他 Magisk 模块：暂无

补充：暂无

**Comment by rhjdvsgsgks** [comment]
和你差不多

- 问题出现时的环境 
Android pie 一加1 只开启了q++

- 问题出现具体情况
抢红包时有几率闪退，且不支持刚更新的q++1.1.10

- 版本
qq770 太极413 magisk模块3.2 b版

**Comment by tiann** [comment]
fixed in https://github.com/tiann/EXposed/releases/tag/4.1.4
