### ISSUE TITLE
太极Magisk4.0无法开机

### ISSUE THREAD

**Issue by Heliumw** [tiann/EXposed#223]
手机型号：PRA-AL00
ROM版本：9.0
Xposed模块：无（太极数据已清除，应该是没启用任何模块吧）
APP：太极

问题描述：刷入太极magisk模块后重启可使用太极，再重启即卡在进入系统的那一瞬间，只显示通知栏和导航栏的返回键，接着就会重启，卸载太极magisk后又能开机了

其他Magisk模块：无论有没有其他模块结果都一样

补充：测试时已清除太极的数据，magisk18.0和18.1情况相同

**Comment by tiann** [comment]
需要提供启动阶段的logcat日志。

**Comment by Heliumw** [comment]
> 需要提供启动阶段的logcat的日志。

请问怎么搞到logcat日志呢

**Comment by Heliumw** [comment]
> 需要提供启动阶段的logcat的日志。

[新建文本文档.txt](https://github.com/tiann/EXposed/files/2844159/default.txt)
logcat在这里

**Comment by tiann** [comment]
正常启动之后，使用root权限删除 /data/system/taichi试试

**Comment by Heliumw** [comment]
> 正常启动之后，使用root权限删除/ data / system / taichi试试

可以了，感谢！
