### ISSUE TITLE
求适配华为荣耀10

### ISSUE THREAD

**Issue by HaleShaw** [tiann/EXposed#229]
手机型号：华为荣耀10普通版：4+64G，COL-AL10
ROM版本：8.1.0.181(C00GT)
Xposed模块：未启用
APP：微信7.0.0

问题描述：
太极4.2.3，4.2.5都试了，太极阴和太极阳两种模式下，都无法创建应用，无法识别到安装的模块。
点击创建应用按钮，不出来应用列表。
在太极阴模式下，有个+号，可以去手动选择APK包，创建上微信。在太极阳模式下没有+号，就完全无法创建应用。创建完应用，也无法在太极应用列表里面找到应用。（且只能选择“文件方式”创建成功，选择“标准安卓方式”也无法创建成功）
创建应用后，去安装模块。模块安装完成，也无法在模块管理里面列出来。
打开模块APP，显示太极没有加载应用，没有启用XPosed模块。

其他Magisk模块：Magisk6和7都试了，v17+和v18+也都试了

补充：
就相当于是太极在华为荣耀10 ，安卓8.1下完全没法用。求大神有时间能够适配，谢谢！

**Comment by tiann** [comment]
你之前使用了其他 Xposed框架，没有删干净。清除干净即可。

**Comment by HaleShaw** [comment]
> 你之前使用了其他 Xposed框架，没有删干净。清除干净即可。

不应该吧。我为了适配这个，我直接三清后，完全重新刷机，都没启用过XPosed框架，然后就直接安装的太极。

**Comment by HaleShaw** [comment]
另外再请问一下，有没有什么方法检测手机里面还残留有xposed框架？比如有哪个目录或哪个文件之类的？

**Comment by tiann** [comment]
/system/xposed.prop？

**Comment by HaleShaw** [comment]
> /system/xposed.prop？

看了手机，里面没有这个目录或者文件。我是专门三清后，完全重新刷机，再安装的太极。刷机后完全没安装过xposed。

**Comment by tiann** [comment]
我觉得你把好几个问题混在一起了，建议你一个个查，别这个不行了换一个方式，那都是不同的问题。

1，太极阴创建列表是空的，显然是因为你没给太极必要的权限，比如查看安装包列表的权限，或者创建应用。
2，太极阳没有创建按钮就是因为有遗留的xposed。可能你三清之后用的太极阴而非阳。
3，我女朋友的手机就是荣耀10，不存在这个问题。

你自己理清思路好好查一查，这些问题都不是同一个问题。

**Comment by HaleShaw** [comment]
非常感谢！已经解决。
按你这说法的确应该是两个问题。
太极阴创建列表是空的，应该就是没有给太极权限，现在已经解决了。主要没想到这个问题，没这方面经验。
现在我用的模块还不是很多，太极阴已经解决，太极阳就再等你后续版本更稳定了来测试。

其实有点想上安卓9.0了，但是我怕我另外一个软件对安卓9.0支持不好，所以一直在犹豫。不然就上9.0去用太极阳了。
再次感谢，也谢谢做出这么好的软件！加油！
