### ISSUE TITLE
小米5 无法触发magisk版本的太极

### ISSUE THREAD

**Issue by ZYMirror** [tiann/EXposed#23]
手机型号：小米5
ROM版本：miui10.2 安卓8.0
Xposed模块：
APP：

问题描述：
一切根据正常步骤，无法触发magisk版本，不提示内测，b版和a版都不行
其他 Magisk 模块：没有其他模块

补充：

**Comment by 06ji** [comment]
我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码

**Comment by ZYMirror** [comment]
> 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码

我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，miui什么版本号

**Comment by 06ji** [comment]
> > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> 
> 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，miui什么版本号

不是官方版。。是官改，miui10 8.10.12

**Comment by ZYMirror** [comment]
> > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > 
> > 
> > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> 
> 不是官方版..是官改，miui10 8.10.12

什么官改呀，星空包，w大的？还是极光或者别的

**Comment by 06ji** [comment]
> > > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > > 
> > > 
> > > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> > 
> > 
> > 不是官方版..是官改，miui10 8.10.12
> 
> 什么官改呀，星空包，w大的？还是极光或者别的

星空包

**Comment by 123676232** [comment]
我也是小米5和你系统一样！问题也一样！无法出发太极面具！

**Comment by 123676232** [comment]
我也是小米5和你系统一样！问题也一样！无法出发太极面具！

**Comment by 123676232** [comment]
我也是小米5和你系统一样！问题也一样！无法出发太极面具！

**Comment by 06ji** [comment]
> > > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > > 
> > > 
> > > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> > 
> > 
> > 不是官方版..是官改，miui10 8.10.12
> 
> 什么官改呀，星空包，w大的？还是极光或者别的

如果是极光的话，要卸载超级授权

**Comment by ZYMirror** [comment]
> > > > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > > > 
> > > > 
> > > > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> > > 
> > > 
> > > 不是官方版..是官改，miui10 8.10.12
> > 
> > 
> > 什么官改呀，星空包，W大的？还是极光或者别的
> 
> 如果是极光的话，要卸载超级授权

我也是星空包，最新的小米5最终稳定版，我刷回去以前的看看

**Comment by 06ji** [comment]
> > > > > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > > > > 
> > > > > 
> > > > > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> > > > 
> > > > 
> > > > 不是官方版..是官改，miui10 8.10.12
> > > 
> > > 
> > > 什么官改呀，星空包，W大的？还是极光或者别的
> > 
> > 
> > 如果是极光的话，要卸载超级授权
> 
> 我也是星空包，最新的小米5最终稳定版，我刷回去以前的看看

莫名其妙。。刷了A，这个有软重启BUG，我又刷了B，太极失效了。。变成普通版太极

**Comment by ZYMirror** [comment]
> > > > > > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > > > > > 
> > > > > > 
> > > > > > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> > > > > 
> > > > > 
> > > > > 不是官方版..是官改，miui10 8.10.12
> > > > 
> > > > 
> > > > 什么官改呀，星空包，W大的？还是极光或者别的
> > > 
> > > 
> > > 如果是极光的话，要卸载超级授权
> > 
> > 
> > 我也是星空包，最新的小米5最终稳定版，我刷回去以前的看看
> 
> 莫名其妙..刷了A，这个有软重启BUG，我又刷了B，太极失效了..变成普通版太极

现在弄好了吗

**Comment by ZYMirror** [comment]
> > > > > > > 我小米5可以的，我面具18版本，有提示输入内测码。坐等内测码
> > > > > > 
> > > > > > 
> > > > > > 我也是面具18版本，不过我的系统是官改版，不是官方版，你是官方版吗，MIUI什么版本号
> > > > > 
> > > > > 
> > > > > 不是官方版..是官改，miui10 8.10.12
> > > > 
> > > > 
> > > > 什么官改呀，星空包，W大的？还是极光或者别的
> > > 
> > > 
> > > 如果是极光的话，要卸载超级授权
> > 
> > 
> > 我也是星空包，最新的小米5最终稳定版，我刷回去以前的看看
> 
> 莫名其妙..刷了A，这个有软重启BUG，我又刷了B，太极失效了..变成普通版太极

嘀嘀嘀，我刷成magisk17.3，再刷模块，终于变成magisk版的太极了

**Comment by ZYMirror** [comment]
> 我也是小米5和你系统一样！问题也一样！无法出发太极面具！

嘀嘀嘀，我刷成magisk17.3，再刷模块，终于变成magisk版的太极了

**Comment by 123676232** [comment]
怎么刷17.3

**Comment by ZYMirror** [comment]
> 怎么刷17.3

https://github.com/topjohnwu/Magisk/releases在这里找18.0的卸载包，和17.3的安装包，用第三方rec刷卸载包把18卸了，再刷17.3的安装包，ok了

**Comment by 123676232** [comment]
我的是官包

**Comment by ZYMirror** [comment]
> 我的是官包

一样刷，没有区别

**Comment by 123676232** [comment]
刚从第三方R刷回来！暂时不考虑刷回去！

**Comment by applo** [comment]
貌似绿色守护的magisk模块会有影响，建议关了再试试

**Comment by ZYMirror** [comment]
> 貌似绿色守护的magisk模块会有影响，建议关了再试试

除了太极的magisk模块，没有任何模块，magisk18怎么试就是不行，换成17.3就可以了
