### ISSUE TITLE
微x模块红包功能用不了

### ISSUE THREAD

**Issue by QiWu666** [tiann/EXposed#238]
手机型号：小米mix2s
ROM版本：miui10.2.1基于安卓p
Xposed模块：qx模块
APP：微信

问题描述：magisk122，只有在点击微信图标打开微信之后才可以抢红包，后台抢不了。

其他Magisk模块：无  正常刷机多次也是无效 在另一台原生安卓p正常

**Comment by tiann** [comment]
后台被MIUI 管制了的原因啊，跟太极有啥关系？
