### ISSUE TITLE
抖音助手不能用 平行空间双开的微信也不能用，求添加

### ISSUE THREAD

**Issue by cutepan** [tiann/EXposed#26]
手机型号：
ROM版本：
Xposed模块：
APP：

问题描述：
抖音助手不能用 平行空间双开的微信也不能用，求添加
其他 Magisk 模块：

补充：

**Comment by tiann** [comment]
fixed in https://github.com/tiann/EXposed/releases/tag/4.1.4

**Comment by tiann** [comment]
太极与 Xposed 的机制完全不同，开放所有插件没有意义。很多插件都是需要重新弄的。
