### ISSUE TITLE
Magisk版太极和Substraum主题冲突

### ISSUE THREAD

**Issue by zodk** [tiann/EXposed#31]
在没刷太极模块前，sub主题一切正常
刷了模块B重启后sub任何叠加层失效。不过可以先禁停模块B重启后可以叠加sub主题，不过在启用模块B 正常重启启用模块B后sub临时正常，再重启一次会导致sub失效。

**Comment by zodk** [comment]
目前只发现和sub主题冲突

**Comment by zodk** [comment]
系统 （天空龙 9.0） Magisk版本 v17.2

**Comment by zodk** [comment]
机型 一加3T

**Comment by tiann** [comment]
duplicated #36
