### ISSUE TITLE
应用变量3.3.2不支持

### ISSUE THREAD

**Issue by fidcz** [tiann/EXposed#39]
应用变量强制更新3.3.2，3.3.1版本无法使用。求支持

**Comment by fidcz** [comment]
3.3.1又开放使用了，不用支持都行了

**Comment by tiann** [comment]
哪里有 3.3.2 ？

**Comment by fidcz** [comment]
酷安有更新，不过应用变量作者说了会联系你的

**Comment by tiann** [comment]
should be fixed in https://github.com/tiann/EXposed/releases/tag/4.1.4
