### ISSUE TITLE
面具版太极bug反馈

### ISSUE THREAD

**Issue by PikaHuan** [tiann/EXposed#41]
太极版本：4.1.3/4.1.4 面具模块b
网易云音乐版本：5.5.2
问题：使用了面具版太极后，网易云音乐（5.5.2）和音量增强器（0.0.27）之间会有冲突，造成网易云无法联网，导致无法登录、获取歌单以及一切联网性操作（据反映少部分使用4.1.3版本的网易云的用户使用正常），同时设置里的 设置下载目录 和 缓存设置 功能都无法打开。而普通版太极没有这个问题出现。关闭音量增强器后一切正常。望解决，谢谢。

**Comment by Jack0001** [comment]
是magisk的锅，在magisk hide里把网易云勾上就行。
