### ISSUE TITLE
magisk-b版刷入后系统无法进入深度睡眠

### ISSUE THREAD

**Issue by Andersorz** [tiann/EXposed#43]
系统：基于AOSP的数个类原生ROM，Android 9.0
刷入magisk太极b版后，太极运行正常，但长时间锁屏下持续掉电，设置里耗电记录中没有太极，Android系统耗电占大头。
禁用magisk太极模块后有所好转。

**Comment by tiann** [comment]
未出现这种情况，还需要确认

**Comment by Andersorz** [comment]
经过几次刷magisk太极的更新，我发现，每次重刷模块的第一次开机，深度休眠都无法启动，无论静置多久都不行，禁用模块后重启正常深度休眠，然后再启用模块重启也不会出现该问题。所以我现在每次刷完模块，都要禁用再启用一遍。。每次重启都会等一段时间看看深度休眠工不工作。。

**Comment by Andersorz** [comment]
4.0版本仍有此问题，好像是Google app助手的原因（不确定）
