### ISSUE TITLE
是否有支持系统全局类模块的计划？

### ISSUE THREAD

**Issue by fanxl666** [tiann/EXposed#49]
手机型号：一加6
ROM版本：公测14版 安卓9.0

问题描述：感谢大神的辛勤付出，目前完美使用中，相信很多人对系统层的模块需求也很大，比如重力工具箱等，不知大神是否有计划适配？感谢

**Comment by tiann** [comment]
刷 A 版，如果稳定，就可以用全局模块。

**Comment by Turroise** [comment]
> 刷 A 版，如果稳定，就可以用全局模块。

之前管理员说要把“UI”和“servers”添加到应用里，前者指的应该是systemui，但是后者指的是什么啊？

**Comment by tiann** [comment]
不用

**Comment by Turroise** [comment]
> 不用

感谢回复 我稍后再试
