### ISSUE TITLE
magisk版反复黑屏重启

### ISSUE THREAD

**Issue by Verlaski** [tiann/EXposed#50]
手机型号：小米8
ROM版本：MIUI 10: 9.1.17
Xposed模块：QX, 微X
APP：QQ, 微信

问题描述：QX微X模块已启用，但是均未生效，QQ: Appid is invalid. 一段时间以后手机黑屏重启，弹窗提示: Find device closed unexpectedly.

其他 Magisk 模块：无

补充：

**Comment by Verlaski** [comment]
Magisk 版本：v17.2

**Comment by tiann** [comment]
刷 3.2 -b ，然后卸载 原来太极创建过的APP。

（请仔细阅读使用说明）
