### ISSUE TITLE
希望支持-运动加速器

### ISSUE THREAD

**Issue by 1105384898** [tiann/EXposed#52]
运动加速器，希望支持一下

**Comment by zhangxuhu** [comment]
附一下连接：https://www.coolapk.com/apk/com.qianbajin.sportaccelerator

**Comment by tiann** [comment]
fixed: https://github.com/tiann/EXposed/releases/tag/4.0.2.5

**Comment by 1105384898** [comment]
面具模块有更新链接吗

**Comment by tiann** [comment]
面具模块不用更新
