### ISSUE TITLE
希望支持-LocationReportEnabler

### ISSUE THREAD

**Issue by Turroise** [tiann/EXposed#53]
手机型号：小米mix2s
ROM版本：miui10.9.1.17
Xposed模块：locationreportenabler

**Comment by tiann** [comment]
这个跟我这没关系吧？

**Comment by Turroise** [comment]
> 这个跟我这没关系吧？

LRE有xposed模块

**Comment by tiann** [comment]
https://repo.xposed.info/module/com.ghostflying.locationreportenabler

这个吗？

**Comment by Turroise** [comment]
> https://repo.xposed.info/module/com.ghostflying.locationreportenabler
> 
> 这个吗？

Yep

**Comment by tiann** [comment]
试下这个：https://github.com/tiann/EXposed/releases/tag/4.0.2.5 看看是否可用。

**Comment by panyuhang93** [comment]
4.2.0.6版本不行，打勾了模块未生效，要添加什么应用吗，还是这是全局模块

**Comment by Turroise** [comment]
> 试下这个：https://github.com/tiann/EXposed/releases/tag/4.0.2.5 看看是否可用。

感谢您的工作，目前该模块似乎已堪用（exposed4.2.1.2），如果在多次重启后仍能保持可用那么就没有问题了（miui下非模块化的lre 在多次重启后有概率失效），之后我会继续在此反馈使用状况！

**Comment by Turroise** [comment]
> > 试下这个：https://github.com/tiann/EXposed/releases/tag/4.0.2.5 看看是否可用。
> 
> 感谢您的工作，目前该模块似乎已堪用（exposed4.2.1.2），如果在多次重启后仍能保持可用那么就没有问题了（miui下非模块化的lre 在多次重启后有概率失效），之后我会继续在此反馈使用状况！

和app版的一样，模块化后依旧会在重启两次后失效

**Comment by tiann** [comment]
这个情况应该跟框架没有关系了，close 了。
