### ISSUE TITLE
怎么让自己的模块被支持

### ISSUE THREAD

**Issue by twlkyao** [tiann/EXposed#54]
自己按照xposed的方法写了个插件，想测试下，发现不支持，怎么才能支持

**Comment by DaFeiMao233** [comment]
edxp

**Comment by DaFeiMao233** [comment]
![操作](https://ooo.0o0.ooo/2019/01/25/5c4a8af280404.jpg)把这里删了就可以自我安慰了，这里是面具太极模块的xp模块兼容性检查

**Comment by twlkyao** [comment]
> ![操作](https://camo.githubusercontent.com/109a0b5634d6143643025eebe469192c816242f7/68747470733a2f2f6f6f6f2e306f302e6f6f6f2f323031392f30312f32352f356334613861663238303430342e6a7067)把这里删了就可以自我安慰了，这里是面具太极模块的xp模块兼容性检查

反编译，然后删除这里？
