### ISSUE TITLE
希望支持新模块-应用翻译器

### ISSUE THREAD

**Issue by panyuhang93** [tiann/EXposed#55]
https://www.coolapk.com/apk/com.lerist.xposed.apptranslator
这个软件挺好用的，虽然有root版，不过会卡，现在的版本api好像失效了，作者说年后再修

**Comment by DaFeiMao233** [comment]
edxp可完美兼容

**Comment by DaFeiMao233** [comment]
酷安搜索GoogleAPP助手

**Comment by panyuhang93** [comment]
稳定吗 @DaFeiMao233 我手机是pixel 2016

**Comment by DaFeiMao233** [comment]
@panyuhang93 我米八青春完美兼容，而且理论兼容所有模块，而且不用挂载软件还可以兼容修改系统

**Comment by tiann** [comment]
fixed https://github.com/tiann/EXposed/releases/tag/4.2.0.6
