### ISSUE TITLE
Magisk模块未生效

### ISSUE THREAD

**Issue by Edgeout** [tiann/EXposed#6]
手机型号：一加3
ROM版本：havoc os 9.0
Xposed模块：尚未启用
APP：尚未启用

问题描述：刷入magisk-taichi-v3.2-b.zip 后，重启手机，太极APP依旧不现实magisk内核，不提示内测

其他 Magisk 模块：MM管理器、busybox for Android NDK、OP3/3T Front camera fix、翔鹤黑体

补充：MM管理器、busybox for Android NDK、OP3/3T Front camera fix、翔鹤黑体

**Comment by tiann** [comment]
把其他模块都关掉，然后再试试。

**Comment by applo** [comment]
想问下楼上的magisk版本号是多少，我是18.0，一加3T的nitrogen，我也无效。我怀疑是magisk版本问题

**Comment by tiann** [comment]
使用 magisk 17.2 试下

**Comment by tiann** [comment]
#23

**Comment by tiann** [comment]
https://github.com/tiann/EXposed/releases/tag/3.3-a
