### ISSUE TITLE
magisk版不显示内核版本号

### ISSUE THREAD

**Issue by arklee** [tiann/EXposed#60]
手机是一加6，系统语言英语，装了太极magisk（几个版本都是）显示内核版本d%，原话，Taichi Magisk Kernel %d actived。我觉得算不上bug吧，一点不影响使用的。

**Comment by tiann** [comment]
这就有点尴尬了。。

**Comment by tiann** [comment]
https://github.com/tiann/EXposed/releases/tag/4.2.0.6
