### ISSUE TITLE
希望支持-抖音国际版和插件（要妳命三千）

### ISSUE THREAD

**Issue by GaHoKwan** [tiann/EXposed#72]
## 模块名字
要妳命三千
## 模块用途
破解国际版抖音地区限制
## 模块版本号
2.0
## 模块安装包
https://repo.xposed.info/module/cn.kwaiching.hook

**Comment by tiann** [comment]
fixed https://github.com/tiann/EXposed/releases/tag/4.0.2.5

**Comment by GaHoKwan** [comment]
更新至4.2.0.7了，依然不支持，fixed？
app https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically
模块 https://repo.xposed.info/module/cn.kwaiching.hook
