### ISSUE TITLE
请更新适配哔哩补丁1.5.6版

### ISSUE THREAD

**Issue by BoringCat** [tiann/EXposed#78]
## 模块名字
哔哩布丁
## 模块版本号
1.5.6
## 模块更新了什么？
适配哔哩哔哩客户端5.37.0
#### 模块本体：
https://drive.google.com/open?id=1AFgibhmOdhn4jtRoCnC2AhSpiZfjSdOM

**Comment by tiann** [comment]
https://github.com/tiann/EXposed/releases/tag/4.0.2.5

**Comment by WickedZX** [comment]
> ## 模块名字
> 哔哩布丁
> 
> ## 模块版本号
> 1.5.6
> 
> ## 模块更新了什么？
> 适配哔哩哔哩客户端5.37.0
> 
> #### 模块本体：
> https://drive.google.com/open?id=1AFgibhmOdhn4jtRoCnC2AhSpiZfjSdOM

新版本的哔哩布丁在哪里发布啊？
