### ISSUE TITLE
请求新增对 森林&庄园 的支持

### ISSUE THREAD

**Issue by TheRainight** [tiann/EXposed#86]
## 模块名字
森林&庄园
## 模块用途
![em.a.m](http://img04.sogoucdn.com/app/a/100520146/7085ef9639123453310803e59efcbdef)
## 模块版本号
1.1.2

## 模块安装包
<http://t.cn/EtciO3G>
## 作者邮箱
<z.houbin@foxmail.com>

**Comment by tiann** [comment]
这个模块我试过了，他检测xp把太极误伤了，用不了
