### ISSUE TITLE
Magisk-3.6a 导致视频播放热重启

### ISSUE THREAD

**Issue by silicer** [tiann/EXposed#89]
手机型号：一加6   6+64
ROM版本：OxygenOS 9.0.3

Xposed模块：
(应该和模块没什么关系)
微信群消息助手 , QQ净化 , QX模块 , 微X模块 , ColorQQ , MDWechat , 哔哩布丁 , 指纹支付

APP：nPlayer  1.5.4.27  ,  Z直播  3.3.0(均未加入太极名单)

问题描述：
3.6b一切稳定。使用3.6a时，在两种播放器均没有加入太极名单的情况下，播放视频或者观看直播会导致手机热重启。热重启的时间可能是在打开视频或者直播几秒后，也可能稳定播放直至切换至主屏幕时热重启。

其他Magisk 模块：
Busybox for Android NDK
Gboard Themes
Magisk Manager for Recovery
OxygenOS Gps Back China
Quick Switch
Universal GMS Doze
翔鹤黑体TazuganeSC+MyriadPro英文（宁静之雨）

补充：

**Comment by tiann** [comment]
机器人疯了

**Comment by caliban511** [comment]
同样问题，机器人确实疯了。
