### ISSUE TITLE
微信斗图神器不生效

### ISSUE THREAD

**Issue by js2854** [tiann/EXposed#98]
手机型号：红米Note5
ROM版本：MIUI 10.2.1.0
Xposed模块：微信斗图神器，微信增强
APP：微信

问题描述：
Magisk版本的斗图神器不生效，非Magisk版本没问题；微信增强也ok

其他Magisk模块：MM

补充：
![_20190129085643](https://user-images.githubusercontent.com/1471787/51876541-d8799980-23a3-11e9-8bed-02b4bfbfd258.jpg)
![_20190129085648](https://user-images.githubusercontent.com/1471787/51876542-d8799980-23a3-11e9-890c-b79068e40661.png)
![_20190129085652](https://user-images.githubusercontent.com/1471787/51876543-d9123000-23a3-11e9-90ea-b25ece1cd16c.png)
![_20190129085749](https://user-images.githubusercontent.com/1471787/51876575-fc3cdf80-23a3-11e9-9386-560ea577505e.png)

**Comment by js2854** [comment]
> https://github.com/tiann/EXposed/releases/tag/TaiChi-4.2.1.2
> 
> 试下这个

升级了taichi 4.2.1.2，重启了微信，还是不生效。

magisk-3.9 没找到地址，能丢个么？

**Comment by js2854** [comment]
magisk-3.9 + taichi 4.2.1.2仍然不生效，可能是个例吧

**Comment by js2854** [comment]
magisk-3.9 + taichi 4.2.1.2仍然不生效，可能是个例吧

**Comment by tiann** [comment]
你那个斗图神器还不支持703版本，与太极无关。

**Comment by js2854** [comment]
是的，发现是斗图神器没适配微信703的原因，现在斗图神器已经适配703，期待太极适配斗图神器703

**Comment by js2854** [comment]
是的，发现是斗图神器没适配微信703的原因，现在斗图神器已经适配703，期待太极适配斗图神器新版

**Comment by js2854** [comment]
是的，发现是斗图神器没适配微信703的原因，现在斗图神器已经适配703，期待太极适配斗图神器新版
